// <auto-generated />
namespace LIDER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202006130207442_SeedProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
